# Generated by Django 5.2.9 on 2026-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='style_image',
            field=models.URLField(max_length=500),
        ),
    ]
