# Generated by Django 5.2.9 on 2026-01-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_cover_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='products/covers/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/details/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='style_image',
            field=models.ImageField(upload_to='products/variants/'),
        ),
    ]
