# Generated by Django 5.2.9 on 2026-01-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_cover_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='style_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/'),
        ),
    ]
