# Generated by Django 5.2.9 on 2026-01-08 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_style_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured_rank',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sales_volume',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='spec',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='style_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='style_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
