# Generated by Django 5.2.9 on 2026-02-26 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('PENDING', '待支付'), ('PAID', '已支付'), ('SHIPPED', '已发货'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=100, verbose_name='物流公司')),
                ('tracking_no', models.CharField(max_length=100, verbose_name='运单号')),
                ('status', models.CharField(choices=[('PENDING', '待发货'), ('SHIPPED', '已发货'), ('DELIVERED', '已签收')], default='SHIPPED', max_length=20)),
                ('shipped_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单发货',
                'verbose_name_plural': '订单发货',
                'db_table': 'order_fulfillments',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品标题')),
                ('product_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='商品图片')),
                ('sku_title', models.CharField(blank=True, default='', max_length=255, verbose_name='SKU 描述')),
                ('quantity', models.PositiveIntegerField(verbose_name='购买数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交单价')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='所属订单')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='商品对象')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'order_items',
                'unique_together': {('order', 'product_id', 'sku_title')},
            },
        ),
        migrations.CreateModel(
            name='FulfillmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='发货数量')),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.fulfillment')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
            ],
            options={
                'db_table': 'order_fulfillment_items',
                'unique_together': {('fulfillment', 'order_item')},
            },
        ),
    ]
