# Generated by Django 5.2.9 on 2026-03-01 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fulfillment',
            constraint=models.UniqueConstraint(fields=('order', 'tracking_no'), name='unique_tracking_per_order'),
        ),
    ]
