# Generated by Django 5.2.9 on 2026-02-24 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product_id', 'sku_title')},
        ),
    ]
