# Generated by Django 5.2.9 on 2026-02-24 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=100, verbose_name='物流公司')),
                ('tracking_no', models.CharField(max_length=100, verbose_name='运单号')),
                ('status', models.CharField(choices=[('PENDING', '待发货'), ('SHIPPED', '已发货'), ('DELIVERED', '已签收')], default='SHIPPED', max_length=20)),
                ('shipped_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单发货',
                'verbose_name_plural': '订单发货',
                'db_table': 'order_fulfillments',
            },
        ),
        migrations.CreateModel(
            name='FulfillmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='发货数量')),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.fulfillment')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
            ],
            options={
                'db_table': 'order_fulfillment_items',
                'unique_together': {('fulfillment', 'order_item')},
            },
        ),
    ]
