# Generated by Django 5.2.9 on 2026-02-25 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_shipped_at"),
        ("products", "0001_initial"),
    ]

    operations = [
        # 1️⃣ 先删除唯一索引，避免 SQLite 删除列时报错
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS order_items_order_id_product_id_sku_title_bde29995_uniq;",
            reverse_sql="CREATE UNIQUE INDEX order_items_order_id_product_id_sku_title_bde29995_uniq "
            "ON orders_orderitem(order_id, product_id, sku_title);",
        ),
        # 2️⃣ 删除旧字段
        migrations.RemoveField(
            model_name="orderitem",
            name="product_id",
        ),
        # 3️⃣ 添加新字段
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="products.product",
                verbose_name="商品对象",
            ),
        ),
    ]
