# Generated by Django 5.2.9 on 2025-12-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='主标题')),
                ('subtitle', models.TextField(blank=True, verbose_name='副标题/说明')),
                ('image', models.ImageField(upload_to='home/banners/', verbose_name='轮播图片')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='按钮文字')),
                ('button_link', models.CharField(blank=True, max_length=255, verbose_name='按钮链接')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='home/features/', verbose_name='图标')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '首页核心卖点',
                'verbose_name_plural': '首页核心卖点',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('image', models.ImageField(upload_to='home/stories/', verbose_name='图片')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '首页品牌理念',
                'verbose_name_plural': '首页品牌理念',
                'ordering': ['order'],
            },
        ),
    ]
