# Generated by Django 5.2.9 on 2026-02-08 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='主标题')),
                ('description', models.TextField(blank=True, verbose_name='副标题/说明')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='按钮文字')),
                ('button_link', models.CharField(blank=True, max_length=255, verbose_name='按钮链接')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '首页核心卖点',
                'verbose_name_plural': '首页核心卖点',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '首页品牌理念',
                'verbose_name_plural': '首页品牌理念',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(max_length=500, verbose_name='图片URL')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.homebanner')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeFeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(max_length=500, verbose_name='图片URL')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.homefeature')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeStoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(max_length=500, verbose_name='图片URL')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.homestory')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
    ]
