# Generated by Django 5.2.9 on 2025-12-29 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homebanner',
            old_name='subtitle',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homefeature',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='homestory',
            name='image',
        ),
        migrations.CreateModel(
            name='HomeBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='home/banners/', verbose_name='图片')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.homebanner')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeFeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ImageField(upload_to='home/features/', verbose_name='图片')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.homefeature')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeStoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='home/stories/', verbose_name='图片')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.homestory')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
    ]
