# Generated by Django 5.2.9 on 2025-12-29 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_subtitle_homebanner_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homefeatureimage',
            old_name='banner',
            new_name='feature',
        ),
        migrations.RemoveField(
            model_name='homestoryimage',
            name='banner',
        ),
        migrations.AddField(
            model_name='homestoryimage',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.homestory'),
            preserve_default=False,
        ),
    ]
