# Generated by Django 5.2.9 on 2026-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_banner_homefeatureimage_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebannerimage',
            name='image',
            field=models.URLField(max_length=500, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='homefeatureimage',
            name='icon',
            field=models.URLField(max_length=500, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='homestoryimage',
            name='image',
            field=models.URLField(max_length=500, verbose_name='图片'),
        ),
    ]
