# Generated by Django 5.2.9 on 2026-01-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_homebannerimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebannerimage',
            name='image',
            field=models.ImageField(upload_to='home/banners/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='homefeatureimage',
            name='icon',
            field=models.ImageField(upload_to='home/features/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='homestoryimage',
            name='image',
            field=models.ImageField(upload_to='home/stories/', verbose_name='图片'),
        ),
    ]
