# Generated by Django 5.2.9 on 2026-01-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_homebannerimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homefeatureimage',
            old_name='icon',
            new_name='image',
        ),
    ]
