# Generated by Django 5.2.9 on 2026-01-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_rename_icon_homefeatureimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebannerimage',
            name='image',
            field=models.URLField(max_length=500, verbose_name='图片URL'),
        ),
        migrations.AlterField(
            model_name='homefeatureimage',
            name='image',
            field=models.URLField(max_length=500, verbose_name='图片URL'),
        ),
        migrations.AlterField(
            model_name='homestoryimage',
            name='image',
            field=models.URLField(max_length=500, verbose_name='图片URL'),
        ),
    ]
