# Generated by Django 5.2.9 on 2026-01-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('address', models.TextField(verbose_name='公司地址')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='手机 / WeChat')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
    ]
