# Generated by Django 5.2.9 on 2026-02-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='公司名称')),
                ('address', models.TextField(blank=True, verbose_name='公司地址')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='手机 / WeChat')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('about_html', models.TextField(blank=True, verbose_name='公司介绍（富文本）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.CreateModel(
            name='RichTextImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='richtext/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company/about/')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='system.companyprofile')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
