# Generated by Django 5.2.9 on 2026-01-01 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='about_html',
            field=models.TextField(blank=True, verbose_name='公司介绍（富文本）'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='公司名称'),
        ),
        migrations.CreateModel(
            name='CompanyAboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company/about/')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='system.companyprofile')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
