# Generated by Django 5.2.9 on 2026-01-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_companyprofile_about_html_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichTextImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='richtext/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
