# Generated by Django 5.2.9 on 2026-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_richtextimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaboutimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='richtextimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
