# Generated by Django 5.2.9 on 2026-01-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_companyaboutimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaboutimage',
            name='image',
            field=models.ImageField(upload_to='company/about/'),
        ),
        migrations.AlterField(
            model_name='richtextimage',
            name='image',
            field=models.ImageField(upload_to='richtext/'),
        ),
    ]
