# Generated by Django 5.2.9 on 2026-02-07 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='评分（1-5）')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='评价图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.orderitem', verbose_name='订单商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价用户')),
            ],
            options={
                'verbose_name': '商品评价',
                'verbose_name_plural': '商品评价',
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('append_content', models.TextField(blank=True, default='', verbose_name='追评内容')),
                ('append_at', models.DateTimeField(blank=True, null=True, verbose_name='追评时间')),
                ('merchant_reply', models.TextField(blank=True, default='', verbose_name='商家回复')),
                ('merchant_replied_at', models.DateTimeField(blank=True, null=True, verbose_name='商家回复时间')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='reviews.review', verbose_name='所属评价')),
            ],
            options={
                'verbose_name': '评价追评/回复',
                'verbose_name_plural': '评价追评/回复',
                'db_table': 'review_replies',
            },
        ),
    ]
