# Generated by Django 5.2.9 on 2026-02-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewreply',
            options={'verbose_name': '商家回复', 'verbose_name_plural': '商家回复'},
        ),
        migrations.RemoveField(
            model_name='reviewreply',
            name='append_at',
        ),
        migrations.RemoveField(
            model_name='reviewreply',
            name='append_content',
        ),
        migrations.AddField(
            model_name='review',
            name='append_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='追评时间'),
        ),
        migrations.AddField(
            model_name='review',
            name='append_content',
            field=models.TextField(blank=True, default='', verbose_name='追评内容'),
        ),
    ]
